import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Provider } from "@/components/ui/provider";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Upskill",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StoreProvider>
          <Provider>
            <Navbar />
            {children}
          </Provider>
        </StoreProvider>
      </body>
    </html>
  );
}
